"""Initial schema.

Creates all tables from the application's SQLAlchemy metadata. Using
``create_all`` here keeps the initial migration exactly in sync with the models;
subsequent schema changes should use ordinary autogenerated migrations.

Revision ID: 0001_initial
Revises:
Create Date: 2026-01-01
"""

from __future__ import annotations

from alembic import op

from palcp_web.db import Base
import palcp_web.models  # noqa: F401  (register tables on Base.metadata)

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
