"""Build the multi-tab Excel workbook from a projection result.

Tabs (in order):

1. **Cover** -- caption, claimant, evaluator, dates, headline totals, disclaimer.
2. **Summary** -- totals by category in all three measures + key assumptions.
3. **Current-Cost Tables** -- itemised current (base-year) dollars by category.
4. **PV Projection** -- itemised lifetime nominal & present value by category.
5. **Annual Schedule** -- year-by-year nominal / discount factor / PV.
6. **Assumptions & Rates** -- every rate, its basis, source, and the formulas.
7. **Data Sources** -- pricing-source provenance + standard source descriptions.
8. **Methodology & Standards** -- IALCP standards, consensus statements, Daubert.
9. **Medical Foundation** -- per-item foundation citations (flags gaps).
10. **Validation** -- the Daubert pre-flight findings.

Each tab is self-explanatory on paper so an exhibit can be lifted out and stand
on its own.
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional

from openpyxl import Workbook
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.worksheet import Worksheet

from ..economics.projection import ProjectionResult
from ..models import Plan
from ..validate import ValidationReport
from . import styles as S
from .content import METHODOLOGY_SECTIONS, SOURCE_DESCRIPTIONS


def _kv(ws: Worksheet, row: int, label: str, value, *, value_is_money=False,
        value_fmt: Optional[str] = None) -> int:
    """Write a 'Label | value' pair (label in col A, value in col B)."""
    lc = ws.cell(row=row, column=1, value=label)
    lc.font = S.LABEL_FONT
    lc.alignment = S.LEFT
    vc = ws.cell(row=row, column=2, value=value)
    vc.font = S.BODY_FONT
    vc.alignment = S.LEFT_WRAP
    if value_is_money:
        S.money(vc)
        vc.alignment = S.RIGHT
    elif value_fmt:
        vc.number_format = value_fmt
    return row + 1


# --------------------------------------------------------------------------- #
# 1. Cover
# --------------------------------------------------------------------------- #
def _cover(wb: Workbook, result: ProjectionResult, version: str, generated_on: str) -> None:
    plan = result.plan
    ws = wb.active
    ws.title = "Cover"
    S.set_widths(ws, [34, 60])
    row = S.title_block(
        ws,
        "Life Care Plan — Cost Projection",
        plan.matter or "Future Medical Care Cost Analysis",
        ncols=2,
    )

    row += 0
    ws.cell(row=row, column=1, value="CASE & EVALUATOR").font = S.CATEGORY_FONT
    row += 1
    row = _kv(ws, row, "Matter / Caption", plan.matter)
    row = _kv(ws, row, "Jurisdiction", plan.jurisdiction)
    row = _kv(ws, row, "Evaluator", plan.evaluator)
    row = _kv(ws, row, "Credentials", plan.evaluator_credentials)
    row = _kv(ws, row, "Report date", plan.report_date)
    row += 1

    ws.cell(row=row, column=1, value="CLAIMANT").font = S.CATEGORY_FONT
    row += 1
    cl = plan.claimant
    row = _kv(ws, row, "Name", cl.name)
    row = _kv(ws, row, "Date of birth", cl.dob)
    row = _kv(ws, row, "Sex", cl.sex)
    row = _kv(ws, row, "Age at report", cl.age_at_report)
    row = _kv(ws, row, "Residence / geographic basis", cl.residence)
    row = _kv(ws, row, "Life expectancy (additional years)",
              round(plan.life_expectancy.additional_years, 1))
    row = _kv(ws, row, "Projection horizon to age",
              round(plan.life_expectancy.terminal_age, 1))
    row += 1

    ws.cell(row=row, column=1, value="HEADLINE TOTALS").font = S.CATEGORY_FONT
    row += 1
    row = _kv(ws, row, "Total current annual cost (Year 1, base $)",
              round(result.first_year_current_cost, 2), value_is_money=True)
    row = _kv(ws, row, "Lifetime cost — current (undiscounted) $",
              round(result.grand_total_current, 2), value_is_money=True)
    row = _kv(ws, row, "Lifetime cost — future (nominal, grown) $",
              round(result.grand_total_nominal, 2), value_is_money=True)
    row = _kv(ws, row, "Lifetime cost — PRESENT VALUE",
              round(result.grand_total_present_value, 2), value_is_money=True)
    ws.cell(row=row - 1, column=1).font = S.BODY_BOLD
    ws.cell(row=row - 1, column=2).font = S.BODY_BOLD
    row += 1

    disclaimer = (
        "This workbook was generated by PA-LCP-Tool v{v} on {d}. It presents cost "
        "projections based on the inputs and published rate/source citations "
        "documented on the Assumptions & Rates and Data Sources tabs. Costs are "
        "stated in current (base-year) dollars, grown to the year incurred using "
        "the cited medical price series, and discounted to present value at the "
        "cited rate using the stated timing convention. Medical care opinions and "
        "their foundation are addressed on the Medical Foundation tab and remain "
        "the responsibility of the qualified clinician(s) of record."
    ).format(v=version, d=generated_on)
    row = S.note(ws, row, disclaimer, ncols=2)
    ws.row_dimensions[row - 1].height = 90
    S.page_setup(ws, landscape=False)


# --------------------------------------------------------------------------- #
# 2. Summary
# --------------------------------------------------------------------------- #
def _summary(wb: Workbook, result: ProjectionResult) -> None:
    plan = result.plan
    ws = wb.create_sheet("Summary")
    S.set_widths(ws, [40, 22, 22, 22])
    row = S.title_block(
        ws, "Summary of Future Care Costs",
        "By category — current, nominal, and present value", ncols=4)

    S.header_row(ws, row, ["Category", "Current (undiscounted)",
                           "Future (nominal)", "Present value"])
    row += 1
    totals = result.totals_by_category()
    for cat in result.categories:
        t = totals.get(cat, {"current": 0, "nominal": 0, "present_value": 0})
        ws.cell(row=row, column=1, value=cat).font = S.BODY_FONT
        for col, key in ((2, "current"), (3, "nominal"), (4, "present_value")):
            c = ws.cell(row=row, column=col, value=round(t[key], 2))
            S.money(c)
        if (row % 2) == 0:
            for col in range(1, 5):
                ws.cell(row=row, column=col).fill = S.BAND_FILL
        row += 1

    # Grand total row.
    c = ws.cell(row=row, column=1, value="TOTAL")
    c.font = S.BODY_BOLD
    c.fill = S.TOTAL_FILL
    for col, val in (
        (2, result.grand_total_current),
        (3, result.grand_total_nominal),
        (4, result.grand_total_present_value),
    ):
        cc = ws.cell(row=row, column=col, value=round(val, 2))
        S.money(cc)
        cc.font = S.BODY_BOLD
        cc.fill = S.TOTAL_FILL
        cc.border = S.BORDER_TOP_DOUBLE
    ws.cell(row=row, column=1).border = S.BORDER_TOP_DOUBLE
    row += 2

    ws.cell(row=row, column=1, value="KEY ASSUMPTIONS").font = S.CATEGORY_FONT
    row += 1
    le = plan.life_expectancy
    dr = plan.discount_rate
    row = _kv(ws, row, "Life expectancy (yrs)", round(le.additional_years, 1))
    row = _kv(ws, row, "Discount rate", dr.annual_rate, value_fmt=S.FMT_PCT2)
    row = _kv(ws, row, "Discount basis / timing", f"{dr.basis} / {dr.timing}")
    row = _kv(ws, row, "Reasonable-value percentile policy",
              f"{plan.percentile_policy:g}th")
    S.note(ws, row + 1,
           "Detailed rate sources and formulas appear on the Assumptions & Rates "
           "tab. Per-item detail appears on the Current-Cost Tables and PV "
           "Projection tabs.", ncols=4)
    S.page_setup(ws, landscape=False)


# --------------------------------------------------------------------------- #
# 3 & 4. Itemised tables (current-cost and PV)
# --------------------------------------------------------------------------- #
def _current_cost(wb: Workbook, result: ProjectionResult) -> None:
    ws = wb.create_sheet("Current-Cost Tables")
    widths = [22, 30, 12, 18, 9, 14, 12, 10, 10, 10, 18]
    S.set_widths(ws, widths)
    row = S.title_block(
        ws, "Current-Cost Life Care Plan Tables",
        "Annualized costs in current (base-year) dollars — no growth, no discount",
        ncols=len(widths))
    headers = ["Category", "Item", "Code", "Source", "%ile", "Unit cost",
               "Freq/Yr", "Every N yr", "1st age", "Last age",
               "Lifetime (undiscounted)"]
    S.header_row(ws, row, headers)
    header_at = row
    row += 1

    by_cat: dict[str, list] = {}
    for r in result.item_results:
        by_cat.setdefault(r.item.category, []).append(r)

    for cat in result.categories:
        rows_for_cat = by_cat.get(cat, [])
        if not rows_for_cat:
            continue
        # Category banner row.
        ws.cell(row=row, column=1, value=cat).font = S.CATEGORY_FONT
        for col in range(1, len(headers) + 1):
            ws.cell(row=row, column=col).fill = S.CATEGORY_FILL
        row += 1
        cat_total = 0.0
        for r in rows_for_cat:
            it = r.item
            ws.cell(row=row, column=1, value=it.category).font = S.BODY_FONT
            ws.cell(row=row, column=2, value=it.item).font = S.BODY_FONT
            ws.cell(row=row, column=3, value=it.code or "").font = S.BODY_FONT
            ws.cell(row=row, column=4, value=it.pricing_source or "").font = S.BODY_FONT
            pcell = ws.cell(row=row, column=5,
                            value=(it.percentile if it.percentile is not None else ""))
            pcell.font = S.BODY_FONT
            pcell.alignment = S.CENTER
            S.money(ws.cell(row=row, column=6, value=round(it.unit_cost, 2)), cents=True)
            ws.cell(row=row, column=7,
                    value=(it.frequency_per_year if it.frequency_per_year else "")
                    ).alignment = S.CENTER
            ws.cell(row=row, column=8,
                    value=(it.every_n_years if it.every_n_years else "")
                    ).alignment = S.CENTER
            ws.cell(row=row, column=9,
                    value=(round(r.first_age, 0) if r.first_age is not None else "")
                    ).alignment = S.CENTER
            ws.cell(row=row, column=10,
                    value=(round(r.last_age, 0) if r.last_age is not None else "")
                    ).alignment = S.CENTER
            S.money(ws.cell(row=row, column=11, value=round(r.current_total, 2)))
            cat_total += r.current_total
            row += 1
        # Category subtotal.
        sc = ws.cell(row=row, column=10, value=f"{cat} subtotal")
        sc.font = S.BODY_BOLD
        sc.alignment = S.RIGHT
        tc = ws.cell(row=row, column=11, value=round(cat_total, 2))
        S.money(tc)
        tc.font = S.BODY_BOLD
        tc.border = S.BORDER_TOP
        row += 1

    # Grand total.
    gc = ws.cell(row=row, column=10, value="LIFETIME TOTAL (undiscounted)")
    gc.font = S.BODY_BOLD
    gc.alignment = S.RIGHT
    gt = ws.cell(row=row, column=11, value=round(result.grand_total_current, 2))
    S.money(gt)
    gt.font = S.BODY_BOLD
    gt.border = S.BORDER_TOP_DOUBLE
    ws.freeze_panes = ws.cell(row=header_at + 1, column=1)
    S.page_setup(ws, landscape=True, repeat_header=header_at)


def _pv_projection(wb: Workbook, result: ProjectionResult) -> None:
    ws = wb.create_sheet("PV Projection")
    widths = [22, 30, 14, 12, 12, 12, 20, 20, 20]
    S.set_widths(ws, widths)
    row = S.title_block(
        ws, "Present-Value Cost Projection",
        "Lifetime cost grown to year incurred and discounted to present value",
        ncols=len(widths))
    headers = ["Category", "Item", "Growth series", "Growth %",
               "Discount %", "Net disc %", "Lifetime current $",
               "Lifetime nominal $", "Present value"]
    S.header_row(ws, row, headers)
    header_at = row
    row += 1

    by_cat: dict[str, list] = {}
    for r in result.item_results:
        by_cat.setdefault(r.item.category, []).append(r)

    d = result.plan.discount_rate.annual_rate
    for cat in result.categories:
        rows_for_cat = by_cat.get(cat, [])
        if not rows_for_cat:
            continue
        ws.cell(row=row, column=1, value=cat).font = S.CATEGORY_FONT
        for col in range(1, len(headers) + 1):
            ws.cell(row=row, column=col).fill = S.CATEGORY_FILL
        row += 1
        sub_cur = sub_nom = sub_pv = 0.0
        for r in rows_for_cat:
            it = r.item
            gr = result.plan.growth_rate_for(it)
            ws.cell(row=row, column=1, value=it.category).font = S.BODY_FONT
            ws.cell(row=row, column=2, value=it.item).font = S.BODY_FONT
            ws.cell(row=row, column=3, value=gr.label).font = S.BODY_FONT
            ws.cell(row=row, column=4, value=r.growth_rate).number_format = S.FMT_PCT2
            ws.cell(row=row, column=5, value=d).number_format = S.FMT_PCT2
            ws.cell(row=row, column=6,
                    value=r.net_discount_rate).number_format = S.FMT_PCT2
            S.money(ws.cell(row=row, column=7, value=round(r.current_total, 2)))
            S.money(ws.cell(row=row, column=8, value=round(r.nominal_total, 2)))
            S.money(ws.cell(row=row, column=9, value=round(r.present_value, 2)))
            sub_cur += r.current_total
            sub_nom += r.nominal_total
            sub_pv += r.present_value
            row += 1
        lc = ws.cell(row=row, column=6, value=f"{cat} subtotal")
        lc.font = S.BODY_BOLD
        lc.alignment = S.RIGHT
        for col, val in ((7, sub_cur), (8, sub_nom), (9, sub_pv)):
            cc = ws.cell(row=row, column=col, value=round(val, 2))
            S.money(cc)
            cc.font = S.BODY_BOLD
            cc.border = S.BORDER_TOP
        row += 1

    gc = ws.cell(row=row, column=6, value="LIFETIME TOTAL")
    gc.font = S.BODY_BOLD
    gc.alignment = S.RIGHT
    for col, val in (
        (7, result.grand_total_current),
        (8, result.grand_total_nominal),
        (9, result.grand_total_present_value),
    ):
        cc = ws.cell(row=row, column=col, value=round(val, 2))
        S.money(cc)
        cc.font = S.BODY_BOLD
        cc.border = S.BORDER_TOP_DOUBLE
    ws.freeze_panes = ws.cell(row=header_at + 1, column=1)
    S.page_setup(ws, landscape=True, repeat_header=header_at)


# --------------------------------------------------------------------------- #
# 5. Annual schedule
# --------------------------------------------------------------------------- #
def _annual_schedule(wb: Workbook, result: ProjectionResult) -> None:
    ws = wb.create_sheet("Annual Schedule")
    cats = result.categories
    base_headers = ["Yr", "Calendar yr", "Age"]
    tail_headers = ["Total nominal", "Discount factor", "Total PV", "Cumulative PV"]
    headers = base_headers + [f"{c} (nom)" for c in cats] + tail_headers
    widths = [6, 12, 8] + [16] * len(cats) + [18, 14, 18, 20]
    S.set_widths(ws, widths)
    row = S.title_block(
        ws, "Annual Cost Schedule",
        "Future (nominal) cost by category, with discounting to present value",
        ncols=len(headers))
    S.header_row(ws, row, headers)
    header_at = row
    row += 1

    cum_pv = 0.0
    for yr in result.year_results:
        cum_pv += yr.total_pv
        ws.cell(row=row, column=1, value=yr.year_index + 1).alignment = S.CENTER
        ws.cell(row=row, column=2,
                value=(yr.calendar_year if yr.calendar_year else "")
                ).alignment = S.CENTER
        ws.cell(row=row, column=3, value=round(yr.age_start, 0)).alignment = S.CENTER
        col = 4
        for c in cats:
            S.money(ws.cell(row=row, column=col,
                            value=round(yr.by_category_nominal.get(c, 0.0), 2)))
            col += 1
        S.money(ws.cell(row=row, column=col, value=round(yr.total_nominal, 2)))
        ws.cell(row=row, column=col + 1,
                value=round(yr.discount_factor, 4)).number_format = "0.0000"
        ws.cell(row=row, column=col + 1).alignment = S.RIGHT
        S.money(ws.cell(row=row, column=col + 2, value=round(yr.total_pv, 2)))
        S.money(ws.cell(row=row, column=col + 3, value=round(cum_pv, 2)))
        if (row % 2) == 0:
            for cc in range(1, len(headers) + 1):
                ws.cell(row=row, column=cc).fill = S.BAND_FILL
        row += 1

    # Total row (nominal + PV).
    tc = ws.cell(row=row, column=3, value="TOTAL")
    tc.font = S.BODY_BOLD
    tc.alignment = S.RIGHT
    col = 4
    for c in cats:
        v = sum(yr.by_category_nominal.get(c, 0.0) for yr in result.year_results)
        cc = ws.cell(row=row, column=col, value=round(v, 2))
        S.money(cc)
        cc.font = S.BODY_BOLD
        cc.border = S.BORDER_TOP
        col += 1
    for offset, val in ((0, result.grand_total_nominal),
                        (2, result.grand_total_present_value)):
        cc = ws.cell(row=row, column=col + offset, value=round(val, 2))
        S.money(cc)
        cc.font = S.BODY_BOLD
        cc.border = S.BORDER_TOP_DOUBLE
    ws.freeze_panes = ws.cell(row=header_at + 1, column=4)
    S.page_setup(ws, landscape=True, repeat_header=header_at)


# --------------------------------------------------------------------------- #
# 6. Assumptions & rates
# --------------------------------------------------------------------------- #
def _assumptions(wb: Workbook, result: ProjectionResult) -> None:
    plan = result.plan
    ws = wb.create_sheet("Assumptions & Rates")
    S.set_widths(ws, [34, 16, 14, 40, 18])
    row = S.title_block(
        ws, "Assumptions & Rate Sources",
        "Every rate and figure relied upon, with its published source", ncols=5)

    ws.cell(row=row, column=1, value="VALUATION").font = S.CATEGORY_FONT
    row += 1
    row = _kv(ws, row, "Report date", plan.report_date)
    row = _kv(ws, row, "Base year", plan.base_year)
    le = plan.life_expectancy
    row = _kv(ws, row, "Age at report", le.age_at_report)
    row = _kv(ws, row, "Life expectancy (additional yrs)",
              round(le.additional_years, 2))
    row = _kv(ws, row, "  └ source", le.source or "(none cited)")
    row = _kv(ws, row, "  └ as of / note", f"{le.as_of} {le.note}".strip())
    row += 1

    dr = plan.discount_rate
    ws.cell(row=row, column=1, value="DISCOUNT RATE").font = S.CATEGORY_FONT
    row += 1
    row = _kv(ws, row, "Annual discount rate", dr.annual_rate, value_fmt=S.FMT_PCT2)
    row = _kv(ws, row, "Basis", dr.basis)
    row = _kv(ws, row, "Cash-flow timing", dr.timing)
    row = _kv(ws, row, "Source", dr.source or "(none cited)")
    row = _kv(ws, row, "As of", dr.as_of)
    row += 1

    ws.cell(row=row, column=1, value="PRICE-GROWTH SERIES").font = S.CATEGORY_FONT
    row += 1
    S.header_row(ws, row, ["Key", "Annual rate", "Net disc.", "Source", "As of"])
    row += 1
    for key, gr in plan.growth_rates.items():
        # Only show series actually referenced by an item, plus 'general'.
        used = any(it.growth_key == key for it in plan.items) or key == "general"
        if not used:
            continue
        ws.cell(row=row, column=1, value=f"{key} — {gr.label}").font = S.BODY_FONT
        ws.cell(row=row, column=2, value=gr.annual_rate).number_format = S.FMT_PCT2
        from ..economics.projection import net_discount_rate
        ws.cell(row=row, column=3,
                value=net_discount_rate(dr.annual_rate, gr.annual_rate)
                ).number_format = S.FMT_PCT2
        sc = ws.cell(row=row, column=4, value=gr.source or "(none cited)")
        sc.font = S.BODY_FONT
        sc.alignment = S.LEFT_WRAP
        ws.cell(row=row, column=5, value=gr.as_of).font = S.BODY_FONT
        row += 1
    row += 1

    ws.cell(row=row, column=1, value="METHOD & FORMULAS").font = S.CATEGORY_FONT
    row += 1
    timing = dr.timing
    offset = {"begin_year": "y", "mid_year": "y + 0.5", "end_year": "y + 1"}[timing]
    formulas = [
        f"Cash-flow time from valuation for projection year y (0-based): m(y) = {offset}  [timing = {timing}].",
        "Future (nominal) cost:  nominal_i(y) = current_i(y) × (1 + g_i)^m(y).",
        "Present value:          pv_i(y) = nominal_i(y) / (1 + d)^m(y).",
        "Equivalent net-discount form:  pv_i(y) = current_i(y) / (1 + r_i)^m(y),  r_i = (1+d)/(1+g_i) − 1.",
        "Reasonable-value percentile policy: {:g}th percentile applied consistently across sources.".format(plan.percentile_policy),
        "Final partial year of life expectancy is prorated by its fractional portion.",
    ]
    for line in formulas:
        row = S.note(ws, row, line, ncols=5)
    if plan.collateral_source_note:
        row += 1
        ws.cell(row=row, column=1, value="COLLATERAL SOURCE NOTE").font = S.CATEGORY_FONT
        row += 1
        row = S.note(ws, row, plan.collateral_source_note, ncols=5)
    S.page_setup(ws, landscape=False)


# --------------------------------------------------------------------------- #
# 7. Data sources
# --------------------------------------------------------------------------- #
def _data_sources(wb: Workbook, result: ProjectionResult) -> None:
    plan = result.plan
    ws = wb.create_sheet("Data Sources")
    S.set_widths(ws, [30, 10, 14, 24, 18, 30])
    row = S.title_block(
        ws, "Data Sources & Provenance",
        "Pricing sources actually used in this plan, with retrieval detail",
        ncols=6)

    S.header_row(ws, row, ["Pricing source", "%ile", "Geographic basis",
                           "Used for (examples)", "Retrieval/effective", "Citation"])
    header_at = row
    row += 1

    # Aggregate per source.
    agg: dict[str, dict] = {}
    for it in plan.items:
        src = it.pricing_source or "(unspecified)"
        a = agg.setdefault(src, {"pcts": set(), "geos": set(), "items": [],
                                 "dates": set(), "cites": set()})
        if it.percentile is not None:
            a["pcts"].add(it.percentile)
        if it.geographic_basis:
            a["geos"].add(it.geographic_basis)
        if len(a["items"]) < 3:
            a["items"].append(it.item)
        if it.retrieval_date:
            a["dates"].add(it.retrieval_date)

    for src, a in agg.items():
        ws.cell(row=row, column=1, value=src).font = S.BODY_FONT
        ws.cell(row=row, column=2,
                value=", ".join(f"{p:g}" for p in sorted(a["pcts"])) or "—"
                ).alignment = S.CENTER
        ws.cell(row=row, column=3, value=", ".join(sorted(a["geos"])) or "—"
                ).alignment = S.LEFT_WRAP
        ws.cell(row=row, column=4, value="; ".join(a["items"])).alignment = S.LEFT_WRAP
        ws.cell(row=row, column=5, value=", ".join(sorted(a["dates"])) or "—"
                ).alignment = S.LEFT_WRAP
        cite = SOURCE_DESCRIPTIONS.get(src, {}).get("url", "")
        ws.cell(row=row, column=6, value=cite).alignment = S.LEFT_WRAP
        row += 1

    row += 1
    ws.cell(row=row, column=1,
            value="STANDARD SOURCE DESCRIPTIONS (reference)").font = S.CATEGORY_FONT
    row += 1
    for name, meta in SOURCE_DESCRIPTIONS.items():
        nc = ws.cell(row=row, column=1, value=name)
        nc.font = S.BODY_BOLD
        nc.alignment = S.LEFT_WRAP
        dc = ws.cell(row=row, column=2, value=meta["desc"])
        ws.merge_cells(start_row=row, start_column=2, end_row=row, end_column=6)
        dc.font = S.BODY_FONT
        dc.alignment = S.LEFT_WRAP
        ws.row_dimensions[row].height = 28
        row += 1
    S.page_setup(ws, landscape=True, repeat_header=header_at)


# --------------------------------------------------------------------------- #
# 8. Methodology & standards
# --------------------------------------------------------------------------- #
def _methodology(wb: Workbook) -> None:
    ws = wb.create_sheet("Methodology & Standards")
    S.set_widths(ws, [4, 110])
    row = S.title_block(
        ws, "Methodology & Professional Standards",
        "Basis for admissibility under Daubert / FRE 702", ncols=2)
    for heading, paragraphs in METHODOLOGY_SECTIONS:
        hc = ws.cell(row=row, column=1, value="")
        hc2 = ws.cell(row=row, column=2, value=heading)
        hc2.font = S.CATEGORY_FONT
        row += 1
        for para in paragraphs:
            bullet = ws.cell(row=row, column=1, value="•")
            bullet.font = S.BODY_FONT
            bullet.alignment = S.LEFT
            cc = ws.cell(row=row, column=2, value=para)
            cc.font = S.BODY_FONT
            cc.alignment = S.LEFT_WRAP
            # Estimate wrapped height.
            est_lines = max(1, int(len(para) / 95) + 1)
            ws.row_dimensions[row].height = 15 * est_lines
            row += 1
        row += 1
    S.page_setup(ws, landscape=False)


# --------------------------------------------------------------------------- #
# 9. Medical foundation
# --------------------------------------------------------------------------- #
def _medical_foundation(wb: Workbook, result: ProjectionResult) -> None:
    ws = wb.create_sheet("Medical Foundation")
    S.set_widths(ws, [24, 32, 50, 14])
    row = S.title_block(
        ws, "Medical Foundation Index",
        "Each item's basis in a treating-provider recommendation or record "
        "(Gunn; Anderson-Moody)", ncols=4)
    S.header_row(ws, row, ["Category", "Item", "Medical foundation", "Status"])
    header_at = row
    row += 1
    missing = 0
    for r in result.item_results:
        it = r.item
        ws.cell(row=row, column=1, value=it.category).font = S.BODY_FONT
        ws.cell(row=row, column=2, value=it.item).font = S.BODY_FONT
        fc = ws.cell(row=row, column=3, value=it.medical_foundation or "")
        fc.font = S.BODY_FONT
        fc.alignment = S.LEFT_WRAP
        if it.medical_foundation:
            status, color = "documented", "006100"
        else:
            status, color = "MISSING", "9C0006"
            missing += 1
        sc = ws.cell(row=row, column=4, value=status)
        sc.font = S.status_font(color)
        sc.alignment = S.CENTER
        row += 1
    row += 1
    S.note(ws, row,
           f"{missing} item(s) lack a documented medical foundation. A "
           f"non-physician planner may not supply medical opinions; items "
           f"without a treating-provider basis are vulnerable to exclusion.",
           ncols=4)
    ws.freeze_panes = ws.cell(row=header_at + 1, column=1)
    S.page_setup(ws, landscape=False, repeat_header=header_at)


# --------------------------------------------------------------------------- #
# 10. Validation
# --------------------------------------------------------------------------- #
def _validation(wb: Workbook, validation: ValidationReport) -> None:
    ws = wb.create_sheet("Validation")
    S.set_widths(ws, [12, 26, 28, 70])
    row = S.title_block(
        ws, "Daubert / FRE 702 Pre-Flight Validation",
        validation.summary(), ncols=4)
    S.header_row(ws, row, ["Severity", "Peer-review domain", "Item", "Finding"])
    header_at = row
    row += 1
    if not validation.findings:
        S.note(ws, row, "No findings. All checks passed.", ncols=4)
    for f in validation.sorted():
        color = {"ERROR": "9C0006", "WARN": "9C6500", "INFO": "385723"}[f.severity]
        sc = ws.cell(row=row, column=1, value=f.severity)
        sc.font = S.status_font(color)
        sc.alignment = S.CENTER
        ws.cell(row=row, column=2, value=f.domain).font = S.BODY_FONT
        ws.cell(row=row, column=3, value=f.item or "—").font = S.BODY_FONT
        mc = ws.cell(row=row, column=4, value=f.message)
        mc.font = S.BODY_FONT
        mc.alignment = S.LEFT_WRAP
        ws.row_dimensions[row].height = 28
        row += 1
    ws.freeze_panes = ws.cell(row=header_at + 1, column=1)
    S.page_setup(ws, landscape=True, repeat_header=header_at)


# --------------------------------------------------------------------------- #
# Orchestration
# --------------------------------------------------------------------------- #
def build_workbook(
    result: ProjectionResult,
    validation: ValidationReport,
    *,
    version: str = "0.1.0",
    generated_on: str = "",
) -> Workbook:
    """Assemble and return the full :class:`~openpyxl.Workbook`."""
    wb = Workbook()
    _cover(wb, result, version, generated_on)
    _summary(wb, result)
    _current_cost(wb, result)
    _pv_projection(wb, result)
    _annual_schedule(wb, result)
    _assumptions(wb, result)
    _data_sources(wb, result)
    _methodology(wb)
    _medical_foundation(wb, result)
    _validation(wb, validation)
    wb.properties.title = "Life Care Plan Cost Projection"
    wb.properties.creator = result.plan.evaluator or "PA-LCP-Tool"
    wb.properties.subject = result.plan.matter
    return wb


def save_workbook(
    result: ProjectionResult,
    validation: ValidationReport,
    path: str,
    *,
    version: str = "0.1.0",
    generated_on: str = "",
) -> str:
    wb = build_workbook(result, validation, version=version, generated_on=generated_on)
    parent = Path(path).parent
    if str(parent) not in ("", "."):
        parent.mkdir(parents=True, exist_ok=True)
    wb.save(path)
    return path
